FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Backend/K8sDemo.SapApi/K8sDemo.SapApi.csproj", "Backend/K8sDemo.SapApi/"]
COPY ["Backend/K8sDemo.Shared/K8sDemo.Shared.csproj", "Backend/K8sDemo.Shared/"]

RUN dotnet restore "Backend/K8sDemo.SapApi/K8sDemo.SapApi.csproj"

COPY . .

RUN dotnet publish "Backend/K8sDemo.SapApi/K8sDemo.SapApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "K8sDemo.SapApi.dll"]