apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RabbitMQ__Host: rabbitmq
  RabbitMQ__ManagementPort: "15672"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RabbitMQ__Username: guest
  RabbitMQ__Password: guest
